name: Reusable Container Build

on:
  workflow_call:
    inputs:
      context:
        type: string
        default: .
      dockerfile:
        type: string
        default: Dockerfile

permissions:
  contents: read

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build image without publishing
        run: docker build --file "${{ inputs.dockerfile }}" "${{ inputs.context }}"
