name: Reusable Flutter CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: .
      flutter-version:
        type: string
        default: '3.32.8'

permissions:
  contents: read

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
