name: Reusable SBOM

on:
  workflow_call:
    inputs:
      path:
        type: string
        default: .

permissions:
  contents: read

jobs:
  sbom:
    name: Generate and upload SBOM
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        with:
          path: ${{ inputs.path }}
          format: spdx-json
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: sbom-spdx
          path: sbom.spdx.json
          if-no-files-found: error
